CREATE TABLE SHIPMENTS (
  ID VARCHAR(50),
  DESTINATION VARCHAR(200)
);

INSERT INTO SHIPMENTS (ID, DESTINATION) values (100, 'The MOON!');
INSERT INTO SHIPMENTS (ID, DESTINATION) values (101, 'The SUN!');